In [44]:
import pandas as pd

In [200]:
df = pd.read_csv("dataSets/class sizes data - sheet 2.csv")
df

    District  Avg Class Size Legal cap
0        1.0           21.21       yes
1        2.0           24.42     FALSE
2        3.0           22.92       yes
3        4.0           20.75       yes
4        5.0           19.00       yes
5        6.0           22.10       yes
6        7.0           21.64       yes
7        8.0           24.18     FALSE
8        9.0           21.67       yes
9       10.0           23.58     FALSE
10      11.0           24.42     FALSE
11      12.0           22.67       yes
12      13.0           20.58       yes
13      14.0           21.33       yes
14      15.0           24.14     FALSE
15      16.0           18.17       yes
16      17.0           22.08       yes
17      18.0           22.75       yes
18      19.0           21.75       yes
19      20.0           24.92     FALSE
20      21.0           24.83     FALSE
21      22.0           24.50     FALSE
22      23.0           19.64       yes
23      24.0           26.38     FALSE
24      25.0           25.92     FALSE
25      26.0           26.83     FALSE
26      27.0           24.58     FALSE
27      28.0           25.08     FALSE
28      29.0           24.17     FALSE
29      30.0           25.08     FALSE
30      31.0           26.08     FALSE
31      32.0           21.25       yes
32       NaN             NaN        16

In [202]:
df.head()

   District  Avg Class Size Legal cap
0       1.0           21.21       yes
1       2.0           24.42     FALSE
2       3.0           22.92       yes
3       4.0           20.75       yes
4       5.0           19.00       yes

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   District        32 non-null     float64
 1   Avg Class Size  32 non-null     float64
 2   Legal cap       33 non-null     object
dtypes: float64(2), object(1)
memory usage: 924.0+ bytes

In [208]:
df.query("`Legal cap` == 'yes'")

    District  Avg Class Size Legal cap
0        1.0           21.21       yes
2        3.0           22.92       yes
3        4.0           20.75       yes
4        5.0           19.00       yes
5        6.0           22.10       yes
6        7.0           21.64       yes
8        9.0           21.67       yes
11      12.0           22.67       yes
12      13.0           20.58       yes
13      14.0           21.33       yes
15      16.0           18.17       yes
16      17.0           22.08       yes
17      18.0           22.75       yes
18      19.0           21.75       yes
22      23.0           19.64       yes
31      32.0           21.25       yes

In [210]:
df.query("`Legal cap` == 'FALSE'")

    District  Avg Class Size Legal cap
1        2.0           24.42     FALSE
7        8.0           24.18     FALSE
9       10.0           23.58     FALSE
10      11.0           24.42     FALSE
14      15.0           24.14     FALSE
19      20.0           24.92     FALSE
20      21.0           24.83     FALSE
21      22.0           24.50     FALSE
23      24.0           26.38     FALSE
24      25.0           25.92     FALSE
25      26.0           26.83     FALSE
26      27.0           24.58     FALSE
27      28.0           25.08     FALSE
28      29.0           24.17     FALSE
29      30.0           25.08     FALSE
30      31.0           26.08     FALSE

In [236]:
avg_class_size_by_district = df.groupby('District')['Avg Class Size'].mean().sort_values(ascending=False)

In [238]:
avg_class_size_by_district.head(5)

District
26.0    26.83
24.0    26.38
31.0    26.08
25.0    25.92
28.0    25.08
Name: Avg Class Size, dtype: float64

In [242]:
avg_class_size_by_district.tail(5)

District
4.0     20.75
13.0    20.58
23.0    19.64
5.0     19.00
16.0    18.17
Name: Avg Class Size, dtype: float64